ALTER TABLE appointments
    ADD COLUMN IF NOT EXISTS intake_data_json TEXT NULL,
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP NULL,
    ADD COLUMN IF NOT EXISTS deleted_by_user_id BIGINT NULL,
    ADD COLUMN IF NOT EXISTS deletion_reason VARCHAR(2000) NULL;

ALTER TABLE reports
    ADD COLUMN IF NOT EXISTS client_id BIGINT NULL,
    ADD COLUMN IF NOT EXISTS counselor_id BIGINT NULL,
    ADD COLUMN IF NOT EXISTS case_id BIGINT NULL,
    ADD COLUMN IF NOT EXISTS appointment_id BIGINT NULL,
    ADD COLUMN IF NOT EXISTS session_id BIGINT NULL,
    ADD COLUMN IF NOT EXISTS report_date TIMESTAMP NULL,
    ADD COLUMN IF NOT EXISTS report_data_json TEXT NULL;
